[package]
name = "dns-message-parser"
version = "0.1.0"
authors = ["LinkTed <link.ted@mailbox.org>"]
edition = "2018"
readme = "README.md"
keywords = ["dns", "parser"]
description = "Libary to encode and decode DNS packets"
license = "BSD-3-Clause"
repository = "https://github.com/LinkTed/dns-message-parser"
categories = [
    "parser-implementations",
    "encoding"
    ]
exclude = [
    ".travis.yml",
    ".travis.sh",
    ".gitignore",
    ]

[badges.travis-ci]
repository = "LinkTed/dns-message-parser"
branch = "master"

[badges.codecov]
repository = "LinkTed/dns-message-parser"
branch = "master"
service = "github"

[dependencies]
num-derive = "0.3.0"
num-traits = "0.2.11"
bytes = "0.5.4"
regex = "1.3.7"
lazy_static = "1.4.0"
getset = "0.1.0"
hex = "0.4.2"
